<?xml version="1.0" encoding="UTF-8"?><record_update table="sysevent_register">
    <sysevent_register action="INSERT_OR_UPDATE">
        <caller_access/>
        <description>Called when a test exception is updated or deleted - sync with IBM Guardium</description>
        <event_name>x_ibmrt_gdpva.ChangeTestException</event_name>
        <fired_by/>
        <queue/>
        <suffix>ChangeTestException</suffix>
        <sys_class_name>sysevent_register</sys_class_name>
        <sys_created_by>admin</sys_created_by>
        <sys_created_on>2022-02-07 15:27:36</sys_created_on>
        <sys_id>84caf5d187a10150387c64280cbb35b4</sys_id>
        <sys_mod_count>2</sys_mod_count>
        <sys_name>x_ibmrt_gdpva.ChangeTestException</sys_name>
        <sys_package display_value="IBM Guardium Vulnerability Assessment" source="x_ibmrt_gdpva">400d30552fa0111049572f2ef699b65a</sys_package>
        <sys_policy/>
        <sys_scope display_value="IBM Guardium Vulnerability Assessment">400d30552fa0111049572f2ef699b65a</sys_scope>
        <sys_update_name>sysevent_register_84caf5d187a10150387c64280cbb35b4</sys_update_name>
        <sys_updated_by>admin</sys_updated_by>
        <sys_updated_on>2022-05-20 19:34:49</sys_updated_on>
        <table>x_ibmrt_gdpva_test_exception</table>
    </sysevent_register>
</record_update>
